on:
  schedule:
    - cron: '7 7 * * *'
# Cancel CI when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: rolling
jobs:
  update:
    runs-on: ubuntu-latest
    name: ubuntu / beta / updated
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install beta
        uses: dtolnay/rust-toolchain@beta
      - name: cargo update
        run: cargo update
      - name: cargo test
        run: cargo test --locked --all-features --all-targets
        env:
          RUSTFLAGS: -D deprecated
